### ISSUE TITLE
Export the rtf.document struct

### ISSUE THREAD

**Issue by dcu** [therox/rtf-doc#3]

**Comment by therox** [comment]
Thanks for contributing, but why do you want exported structs?

**Comment by dcu** [comment]
Main reason is to be able to pass docs, paragraphs, texts, etc to my own functions. 

if you run `golint` and `govet` on code it'll tell you this and other stuff that can be improved

**Comment by therox** [comment]
Ok. I thought that you do not need to pull out the structure skeleton outward, since there are all the necessary functions. Just instance.
